"""empty message

Revision ID: 05bb317b4184
Revises: e5f9fad78aaf
Create Date: 2021-09-20 16:22:04.642063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bb317b4184'
down_revision = 'e5f9fad78aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subir_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('precio', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subir_productos')
    # ### end Alembic commands ###
