"""empty message

Revision ID: 3bcff7ef289f
Revises: 05bb317b4184
Create Date: 2021-09-20 18:57:01.662764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bcff7ef289f'
down_revision = '05bb317b4184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subir_productos')
    op.add_column('product', sa.Column('price', sa.String(length=200), nullable=False))
    op.add_column('product', sa.Column('description', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'description')
    op.drop_column('product', 'price')
    op.create_table('subir_productos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('precio', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='subir_productos_pkey')
    )
    # ### end Alembic commands ###
