"""empty message

Revision ID: 3e099b795027
Revises: 28af73b13a96
Create Date: 2021-11-17 12:03:34.059064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e099b795027'
down_revision = '28af73b13a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_img', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_img')
    # ### end Alembic commands ###
