"""empty message

Revision ID: 56b88a0898da
Revises: 57e4e5808118
Create Date: 2021-09-16 17:19:56.325383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b88a0898da'
down_revision = '57e4e5808118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(length=16), nullable=False))
    op.create_unique_constraint(None, 'user', ['nickname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
